
controller_frequency: 6

TrajectoryPlannerROS:
  max_vel_x: 0.7
  min_vel_x: -0.7
  max_vel_theta: 1
  min_vel_theta: -1
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 1.5
  acc_lim_x: 1.5
  acc_lim_y: 1.5

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  sim_time: 1.5
  sim_granularity: 0.025
  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_scoring: false

  vx_samples: 3
  vtheta_samples: 20

  holonomic_robot: false
